name: merge-main-into-small-image.yml
on:
  pull_request:
    branches:
      - main   
    types:
      - closed
jobs:
  merge-main-into-small-image:
    runs-on: ubuntu-latest
    
    steps:
    - name: Merge with main
      if: github.event.pull_request.merged == true
      run: |
        git checkout small-image
        git merge main --no-ff --no-edit
        git push origin small-image
